version: '3.4'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8340:80"

  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "8433:1433"
    volumes:
      - mse-sqlserver:/var/opt/mssql

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  broker:
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "29092:29092"
      - "9092:9092"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${MSE_AZURE_IDENTITY_DB:-Server=sqlserver;Database=MicroservicesExample.Service.IdentityDb;User Id=sa;Password=Pass@word}
      - MvcClient=http://${MSE_EXTERNAL_DNS_NAME_OR_IP}:8100
      - UseCustomizationData=True
    ports:
      - "8105:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=broker:29092
      - PurchaseUrl=http://web-example-apigw
      - IdentityUrl=http://${MSE_EXTERNAL_DNS_NAME_OR_IP}:8105
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
    ports:
      - "8100:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HealthChecksUI__HealthChecks__0__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__1__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webmvc/hc
      - HealthChecksUI__HealthChecks__2__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://catalog-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Web Example Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://web-bff-aggregator/hc
    ports:
      - "8107:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${MSE_AZURE_IDENTITY_DB:-Server=sqlserver;Database=MicroservicesExample.Service.CatalogDb;User Id=sa;Password=Pass@word}
      - PicBaseUrl=${MSE_STORAGE_CATALOG_URL}
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "8101:80"
      - "9101:81"

  web-bff-aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
      - CatalogUrlHC=http://catalog-api/hc
      - IdentityUrlHC=http://identity-api/hc
      - IdentityUrlExternal=http://${MSE_EXTERNAL_DNS_NAME_OR_IP}:5105
    ports:
      - "8121:80"

  web-example-apigw:
    volumes:
      - ./ApiGateways/Envoy/Config/WebExample:/etc/envoy
    ports:
    - "8202:80"
    - "15202:8001"

volumes:
  mse-sqlserver:
    external: false


